collector draft
apache/incubator-devlake pull request #1968
Opened 2022-05-23 03:59 UTC by thenicetgp

# draft 
add two file
plugins/gitlab/models/issue.go 和 plugins/gitlab/task/issue_collector.go

issue.go里的GitlabIssue和GithubIssue的结构基本一致，repoId换成了ProjectId

issue_collector.go和github里的也基本一致
其中需要修改url

查询到
<img width="742" alt="截屏2022-05-23 11 51 20" src="https://user-images.githubusercontent.com/47466847/169740042-45441c4d-2552-4fbf-8d9d-9330c1f65a47.png">

故url修改为
UrlTemplate: "projects/{{ .Params.ProjectId }}/issues“

2022-05-23 13:21 UTC, warren830 commented on plugins/gitlab/tasks/issue_collector.go
> +			query.Set("direction", "asc")
please check if gitlab use `direction` and `since`, I think it might use other param names for this

2022-05-23 13:22 UTC, warren830 commented on plugins/gitlab/tasks/issue_convertor.go
> +			if issue.State == "closed" {
please check the value of issue.State

2022-05-23 13:25 UTC, warren830 requested changes
Great Job!

2022-05-23 13:25 UTC, warren830 commented on plugins/gitlab/tasks/issue_convertor.go
> +				domainIssue.Status = ticket.DONE
same above

2022-05-23 13:25 UTC, warren830 commented on plugins/gitlab/tasks/issue_convertor.go
> +			if issue.State == "closed" {
and there is a OriginalStatus need to be assigned value

2022-05-23 13:25 UTC, warren830 commented on plugins/gitlab/tasks/issue_extractor.go
> +			if body.IssueType != "ISSUE" {
please check if there is a IssueType

2022-05-24 02:50 UTC, thenicetgp commented on plugins/gitlab/tasks/issue_extractor.go
> +			if body.IssueType != "ISSUE" {
I checked, the answer is yes

2022-05-24 03:16 UTC, thenicetgp commented on plugins/gitlab/tasks/issue_convertor.go
> +			if issue.State == "closed" {
How to understand “OriginalStatus need to be assigned value”, is there any other place that needs to be assigned a value?

2022-05-25 10:22 UTC, thenicetgp commented on plugins/gitlab/tasks/issue_collector.go
> +			since = &latestUpdated.GitlabUpdatedAt
maybe not GitlabUpdatedAt

2022-05-25 14:10 UTC, warren830 approved these changes
LGTM

2022-05-25 14:15 UTC, warren830 commented on plugins/gitlab/tasks/issue_extractor.go
> +		TimeEstimate 		int
this one should be extracted
and convert to OriginalEstimateMinutes

2022-05-25 14:16 UTC, warren830 commented on plugins/gitlab/tasks/issue_extractor.go
> +		TotalTimeSpent 		int
similar to above

2022-05-26 04:18 UTC, warren830 commented on plugins/gitlab/tasks/issue_collector.go
> +			since = &latestUpdated.GitlabUpdatedAt
yes

2022-05-26 04:32 UTC, warren830 requested changes
great job, some minor issues

2022-05-26 04:32 UTC, warren830 commented on plugins/gitlab/models/migrationscripts/archived/issue.go
> +}
move all code of this file to update_schemas20220525, and delete this file

2022-05-26 04:32 UTC, warren830 commented on plugins/gitlab/models/migrationscripts/archived/issue_label.go
> +}
move all code of this file to update_schemas20220525, and delete this file

2022-05-26 04:32 UTC, warren830 commented on plugins/gitlab/tasks/issue_extractor.go
> +		ClosedAt:        helper.Iso8601TimeToTime(issue.GitlabClosedAt),
this seems not right

2022-05-26 04:32 UTC, warren830 commented on plugins/gitlab/tasks/issue_extractor.go
> +	ProjectId    int `json:"id"`
should be `json:project_id`

2022-05-26 07:11 UTC, thenicetgp commented
data in _raw_gitlab_api_issues(raw layer)
<img width="1053" alt="截屏2022-05-26 14 46 15" src="https://user-images.githubusercontent.com/47466847/170436549-1984f59d-ea33-43ce-a2b0-32a138daef7e.png">
data in _tool_gitlab_issues(tool layer)
<img width="1347" alt="截屏2022-05-26 14 51 51" src="https://user-images.githubusercontent.com/47466847/170436581-30534919-0e32-4286-b569-7857b4988ae9.png">
data in issues(domain layer)
<img width="1369" alt="截屏2022-05-26 14 52 15" src="https://user-images.githubusercontent.com/47466847/170436612-21a5c880-2bf9-43a4-b711-5cd7f42fd393.png">

2022-05-26 07:38 UTC, warren830 approved these changes
LGTM

2022-05-26 12:05 UTC, merged