issues/1914: refactor run() method
apache/incubator-devlake pull request #2050
Opened 2022-05-31 22:10 UTC by keon94

### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [ ] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation
- [ ] This PR is using a `label` (bug, feature etc.)
- [ ] My code is has necessary documentation (if appropriate)
- [ ] I have added any relevant tests
- [ ] This section (**⚠️ &nbsp;&nbsp;Pre Checklist**) will be removed when submitting PR

# Summary

### Does this close any open issues?
https://github.com/apache/incubator-devlake/issues/1914

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

2022-06-04 06:07 UTC, hezyin commented on plugins/gitextractor/parser/libgit2.go
> +	commitFile, err = l.generateCommitFileFromDiff(commitSha, diff)
@keon94 This PR splits the original giant `run` function pretty well except this `generateCommitFileFromDiff` function. In fact, the code from line 256 to 264 should live together with the logic in `generateCommitFileFromDiff`. For each diff, we extract and store multiple `commitFile` into the database. Line 256 to 264 is just handling the last one.

2022-06-06 01:11 UTC, klesh commented
I wonder if it would be better to make them 3 different subtasks.

2022-06-07 03:07 UTC, keon94 commented on plugins/gitextractor/parser/libgit2.go
> +	commitFile, err = l.generateCommitFileFromDiff(commitSha, diff)
made that change

2022-06-07 03:07 UTC, keon94 commented
@klesh my latest commit breaks it into 3 subtasks, but the problem is there is no easy way (from my understanding) to cache the cloned repo so that after it is cloned first it gets reused by the remaining two. So right now we end up cloning the repo 3 times. I think we'd need a broader framework enhancement to support a shared state between subtasks, as well as the ability to close/release this shared state after the subtasks are complete.
cc @hezyin

2022-06-08 06:36 UTC, klesh commented
> @klesh my latest commit breaks it into 3 subtasks, but the problem is there is no easy way (from my understanding) to cache the cloned repo so that after it is cloned first it gets reused by the remaining two. So right now we end up cloning the repo 3 times. I think we'd need a broader framework enhancement to support a shared state between subtasks, as well as the ability to close/release this shared state after the subtasks are complete. cc @hezyin

Why not? in `jira` or other data source plugins, we **shared** `apiclient` across multiple subtasks, we can use the same technique here.

2022-06-08 17:11 UTC, keon94 commented
> > @klesh my latest commit breaks it into 3 subtasks, but the problem is there is no easy way (from my understanding) to cache the cloned repo so that after it is cloned first it gets reused by the remaining two. So right now we end up cloning the repo 3 times. I think we'd need a broader framework enhancement to support a shared state between subtasks, as well as the ability to close/release this shared state after the subtasks are complete. cc @hezyin
> 
> Why not? in `jira` or other data source plugins, we **shared** `apiclient` across multiple subtasks, we can use the same technique here.

@klesh Do we have a way of cleaning up after all the subtasks are done though? Something like a shutdown hook that we can define and execute? That'll be needed for this case to remove the cloned repo after the collections are done

2022-06-09 01:24 UTC, klesh commented
> > > @klesh my latest commit breaks it into 3 subtasks, but the problem is there is no easy way (from my understanding) to cache the cloned repo so that after it is cloned first it gets reused by the remaining two. So right now we end up cloning the repo 3 times. I think we'd need a broader framework enhancement to support a shared state between subtasks, as well as the ability to close/release this shared state after the subtasks are complete. cc @hezyin
> > 
> > 
> > Why not? in `jira` or other data source plugins, we **shared** `apiclient` across multiple subtasks, we can use the same technique here.
> 
> @klesh Do we have a way of cleaning up after all the subtasks are done though? Something like a shutdown hook that we can define and execute? That'll be needed for this case to remove the cloned repo after the collections are done

Good question, no, we don't, while I think this is a legitimate feature, we should add a method to release resources.
But for this particular scenario, shouldn't we just keep the repo, and do `git pull` in successive collections to speed things up ?

2022-06-09 04:46 UTC, keon94 commented
> > > > @klesh my latest commit breaks it into 3 subtasks, but the problem is there is no easy way (from my understanding) to cache the cloned repo so that after it is cloned first it gets reused by the remaining two. So right now we end up cloning the repo 3 times. I think we'd need a broader framework enhancement to support a shared state between subtasks, as well as the ability to close/release this shared state after the subtasks are complete. cc @hezyin
> > > 
> > > 
> > > Why not? in `jira` or other data source plugins, we **shared** `apiclient` across multiple subtasks, we can use the same technique here.
> > 
> > 
> > @klesh Do we have a way of cleaning up after all the subtasks are done though? Something like a shutdown hook that we can define and execute? That'll be needed for this case to remove the cloned repo after the collections are done
> 
> Good question, no, we don't, while I think this is a legitimate feature, we should add a method to release resources. But for this particular scenario, shouldn't we just keep the repo, and do `git pull` in successive collections to speed things up ?

well, the existing collector code was "closing" (removing) the repo after it was done with all 3 collections, so we'd want to be doing the same here too. If we don't do that, we'd be leaking files on the filesystem. I've made an enhancement to support this in my latest commit: An extension of the PluginTask API that lets the user close any shared resources if they want to. I ran it on one repo and it seems ok. Let me know what you think.

2022-06-09 13:57 UTC, klesh commented
@keon94 Ok, let's keep the current behavior, and add this `release` interface.

2022-06-10 06:12 UTC, hezyin requested changes
@keon94 Good work, Keon. Please see my comments for a quick review. I'll test this PR tomorrow.

2022-06-10 06:12 UTC, hezyin commented on plugins/gitextractor/parser/repo.go
> +func (r *GitRepo) storeCommitFileFromDiff(commitSha string, diff *git.Diff) error {
Since we're storing multiple `code.CommitFile`, maybe `storeCommitFilesFromDiff` is a more appropriate name.

2022-06-10 06:12 UTC, hezyin commented on plugins/gitextractor/tasks/git_repo_collector.go
> +	subTaskCtx.SetProgress(0, -1)
Here we may have an opportunity to improve progress reporting for git extractor plugin. IIRC, we set the progress to `-1` when we don't know how many total items need to be processed. If we were able to figure out how many commits/branches/tags are there, then maybe we can set progress to that number before the collection process begins, and increments the progress by 1 in each iteration.

2022-06-10 06:12 UTC, hezyin commented on plugins/gitextractor/parser/libgit2.go
>  type LibGit2 struct {
I wonder if we still need the `LibGit2` struct. Its fields aren't actively used by its methods. Maybe we can make those methods simply function without `LibGit2` as their receivers and move useful fields into `GitRepo` struct directly. Let me know if you think we still need `LibGit2` struct.

2022-06-13 18:56 UTC, hezyin commented
@keon94 Hey Keon, thanks for addressing all the previous review comments. The PR looks good. Two last things:

1. Since `LibGit2` struct is just used for creating a `GitRepo` struct now, what do you think of renaming `LibGit2` struct to something like `GitRepoCreator` so it's more apparent to future developers?
2. Could you please compare the performance of the plugin before and after this PR for a relatively large git repository? I'm not sure how costly it is for libgit2 to iterate through the entire odb to get the counts, so better do a perf test to be sure. And when you do this comparison, it would be nice to verify that the old and new code creates the same amount of records in the database as well. Thanks!

2022-06-13 23:08 UTC, keon94 commented
@hezyin There is no significant time difference either way when I test our DevLake fork on my machine (~21s), so I think it's okay to get the counts. Checked the database too and the table sizes are the same.

2022-06-14 06:14 UTC, hezyin approved these changes
LGTM

2022-06-14 07:08 UTC, klesh reviewed
The quality of the implementation is great.
I have left some minor comments.
And please fix the linting issues (Not including "Unchanged files")

2022-06-14 23:09 UTC, keon94 commented on plugins/gitextractor/parser/clone.go
> +		return nil, err
The only issue with that is, the GitRepo object won't be initialized so we can't call Close() on it. I can work around that too, but that'll also add complexity. I'll try to clean the code up here to make it easier to follow

2022-06-15 01:12 UTC, keon94 commented on plugins/gitextractor/parser/repo.go
> +func (r *GitRepo) CollectTags(_ core.SubTaskContext) error {
The struct tracks the taskContext, but these methods are using the subtask context to increment each subtask's progress (actually L127 here needs to be fixed)

2022-06-15 01:16 UTC, keon94 commented on plugins/gitextractor/parser/repo.go
> +func (r *GitRepo) CollectTags(_ core.SubTaskContext) error {
When doing that, the taskContext field becomes unused, so I think I can just remove that

2022-06-15 01:27 UTC, klesh commented on plugins/gitextractor/parser/repo.go
> +func (r *GitRepo) CollectTags(_ core.SubTaskContext) error {
Aah, yes, you are correct. please do so

2022-06-15 02:21 UTC, keon94 commented on plugins/gitextractor/parser/clone.go
> +		return nil, err
I went with wrapping the whole temp directory logic in a function to keep the clone functions clean. Let me know what you think

2022-06-15 07:29 UTC, klesh approved these changes
LGTM

2022-06-15 07:47 UTC, merged