Issues/3329 entity
apache/incubator-devlake pull request #3496
Opened 2022-10-20 01:15 UTC by likyh

# Summary

1. Commit1: change names to `entity` in `useTransformationsManager.jsx`; use Entity as base model for all EntityObjects
2. Commit2: Rename to `entity` or `dataEntity` to `dataDomain`.
![image](https://user-images.githubusercontent.com/3294100/196833512-c9e96ea4-2378-4d31-8fea-7e16e2208967.png)
3. Commit3: Rename `project/board` to `scopeEntity`; rename `project/board` to `scopeEntity`.
4. Commit4/5: fix some jira and jenkins bug
    1. Fix #3547
    2. Fix #3518 It's a rebase bug
    3. Fix #3519 Now old jenkins data will be filtered
    4. add jobName to jenkins default config-samples
    5. use icon for jira board selector
    6. use the same way for BOARDS_ENDPOINT request
    7. search jira boards immediately as default without search text ![image](https://user-images.githubusercontent.com/3294100/197461286-5d0a1fe9-8388-4941-a351-6b5af1b57bc1.png)

    8. use board name from Lake db instead of jira API ![image](https://user-images.githubusercontent.com/3294100/197461061-32b86304-b983-4718-b50e-034feaddb4a2.png)
5. Commit6: fix for old Jenkins job
6. Commit7/8: fix rebase bug and some bugs in another PR

### Does this close any open issues?
Closes #3329 #3478 #3448

2022-10-24 12:14 UTC, e2corporation commented
@likyh This PR will be on-hold in the queue until Part 1 of Plugin Registry (#2886) is completed & merged.

2022-10-24 12:17 UTC, e2corporation commented on config-ui/src/components/blueprints/create-workflow/DataScopes.jsx
> +                                new GitHubProject({
This would mean all scope entities are GitHub Projects? Models need to be instantiated by the Provider associated with the entity. ie. `GitHubProject` vs `GitlabProject` vs `JenkinsJob` etc.

2022-10-24 12:19 UTC, e2corporation commented on config-ui/src/hooks/data-scope/useTransformationsManager.jsx
> +        key = entity?.id
We should be using the accessory function instead, `entity.getConfiguredEntityId()`
```suggestion
        key = entity?.getConfiguredEntityId()
```

2022-10-24 12:20 UTC, e2corporation commented on config-ui/src/hooks/data-scope/useTransformationsManager.jsx
> +        key = entity?.id
```suggestion
        key = entity?.getConfiguredEntityId()
```

2022-10-24 12:21 UTC, likyh commented on config-ui/src/components/blueprints/create-workflow/DataScopes.jsx
> +                                new GitHubProject({
https://github.com/apache/incubator-devlake/pull/3496/files#diff-14f5220fdc068ccea4c51287ebc5ba3b26882d1e542d87daff33c5470207525cR132-R134

Here is the github repo input. There is no other entity

2022-10-24 12:23 UTC, e2corporation commented on config-ui/src/models/Connection.js
> + * @property {<Array[DataDomain]>} dataDomains
Is this valid JSDoc format for specifying array of type?
```suggestion
 * @property {<Array<DataDomain>>} dataDomains
```

2022-10-24 12:45 UTC, e2corporation commented on config-ui/src/components/blueprints/create-workflow/DataScopes.jsx
> +                                new GitHubProject({
@likyh I see, it looks like the `TagInput` component I created earlier is limited for Github use only. Ideally this `<TagInput>.....` sub-component should be extracted in the future to `ProjectsSelector`

2022-10-31 12:13 UTC, likyh commented on config-ui/src/hooks/data-scope/useTransformationsManager.jsx
> +        key = entity?.id
changed by other PR.

2022-10-31 13:45 UTC, likyh commented on config-ui/src/models/Connection.js
> + * @property {<Array[DataDomain]>} dataDomains
fixed

2022-10-31 14:44 UTC, likyh commented
@e2corporation rebased, need your review

2022-11-01 03:20 UTC, mintsweet submitted a review, later dismissed
This PR content is really too much.😂

2022-11-01 06:21 UTC, likyh commented
> This PR content is really too much.😂

😂 Yeah, lots of refactors are related. You can review commits one by one. I split them into different commits.

2022-11-03 13:41 UTC, e2corporation requested changes
@likyh Overall the PR is in good shape and headed in the right direction please review feedback on the following items, and resolve or dismiss them if the findings are not valid. I think the Connection ID issue is definitely relevant now that entities  are merged into one var.

1. Conflicts with using Connection.ID alone for Scope Entities Group
2. Initial state of Data Scopes Dropdown Selector for Blueprint MODIFY Mode

2022-11-03 14:06 UTC, e2corporation commented on config-ui/src/components/blueprints/ProviderTransformationSettings.jsx
> -  const {
To clarify, while `props` is being spread and these props are not technically in use, I think it's useful to reference these props in case this file is further extended and this makes it clear from a documentation standpoint _what_ props we expected `ProviderTransformationSettings` to depend on. If you choose to remove them, move the props to a DocBlock comment instead.

It's cleaner to to just spread `props` from a development standpoint in case we want to extend dependencies to all transformation settings components, we only have to make that change in one place (where ProviderTransforationSettings is implemented)

2022-11-03 14:27 UTC, likyh commented on config-ui/src/components/blueprints/ProviderTransformationSettings.jsx
> -  const {
fixed

2022-11-03 14:27 UTC, likyh commented on config-ui/src/models/Entity.js
> + * @typedef {object} GitHubProject
fixed

2022-11-03 14:28 UTC, likyh commented on config-ui/src/components/blueprints/DataScopesGrid.jsx
> +              {[
use `c.plugin.getMultiConnection`? But I'm not sure if `azure/bitbucket/gitee/tapd` have a title.

2022-11-03 14:33 UTC, likyh commented on config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx
> +        Array.isArray(scopeEntities) ? scopeEntities[0] : null
`activeTransformation` is deps on `configuredScopeEntity`, I guess.

2022-11-03 14:45 UTC, e2corporation commented on config-ui/src/components/blueprints/DataScopesGrid.jsx
> +              {[
In this particular scenario it's not related to multi-connection, we mainly need to know If this provider has a concept of Entity. So this is why we can simply call a check for the `coniguredEntityId()` or extend the models with a new prop to represent this trait.

Another refactor idea for replacing all of these is to add set of memo consts to Transformations Manager that represents groups of Providers that **Have** certain traits or that **Can** do certain actions or **Use** certain features, this way the arrays are centralized in one place. Ideally we should stop using these types of arrays except in limited feature scenarios, and resort to other alternatives that can work dynamically for all plugins in the Registry. This would also be done by extending the Entity Data Model props where needed to add more prop checks.

```jsx
// Sample Array Replacements for Provider Grouped Traits (Abstract)
function useTransformationsManager() {
....

// Grouped Entity Traits & Behaviors

const ProvidersThatHaveEntities = useMemo(() => [Providers.GITHUB, Providers.JIRA], [Providers])
const ProvidersThatHaveWebhooks = useMemo(() => [Providers.DORA], [Providers])
const ProvidersThatCanDeploy = useMemo(() => [Providers.GITHUB, Providers.GITLAB], [Providers])
const ProvidersThatCanExpire = useMemo(() => [Providers.GITEE, Providers.TAPD], [Providers])



....
}
```

2022-11-03 14:50 UTC, e2corporation commented on config-ui/src/components/blueprints/create-workflow/DataScopes.jsx
> +        [configuredConnection.id]: scopeEntities
Ok, this was another reason why I noted Index ID was important within the code comments when I setup the all provider connections map. I think it would be ideal to use a generated key like we do with transformations manager for improved consistency.

2022-11-03 14:52 UTC, e2corporation commented on config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx
> +        Array.isArray(scopeEntities) ? scopeEntities[0] : null
If you Edit a blueprint's Data Connection with multiple projects/boards, is the project dropdown selector's initial rendering correctly? If so this comment can be resolved/dismissed.

2022-11-03 14:53 UTC, likyh commented on config-ui/src/components/blueprints/DataScopesGrid.jsx
> +              {[
`coniguredEntityId()` is defined in entity. But here `c` means `DataScopeConnection`.
Defined a new function in `DataScopeConnection`?
```
function hasScopeEntities() {
    return this.scopeEntities > 0
}
```

I agree with `ProvidersThatXXXX`.

2022-11-03 14:54 UTC, e2corporation commented on config-ui/src/components/blueprints/DataScopesGrid.jsx
> +              {[
Yea adding something to a Model in scope of this logic would be fine as well.

2022-11-03 14:55 UTC, e2corporation commented
@likyh PR #3666 should be merged before this one Ideally.

2022-11-03 14:58 UTC, e2corporation commented on config-ui/src/components/blueprints/ProviderTransformationSettings.jsx
> +      provider,
The reason for using the HOC function is so that spreading `...props` is much cleaner and less code, and there will be no need to maintain these props manually.

2022-11-03 14:59 UTC, e2corporation approved these changes
@likyh @mintsweet Nice refactoring, LGTM (After key Code Review items are resolved, and after #3666 is merged)

2022-11-03 15:14 UTC, likyh commented on config-ui/src/components/blueprints/DataScopesGrid.jsx
> +              {[
fixed

2022-11-03 15:15 UTC, likyh commented on config-ui/src/components/blueprints/ProviderTransformationSettings.jsx
> +      provider,
ok, although I don't agree with usage like this, fixed.

2022-11-03 15:15 UTC, e2corporation approved these changes
@likyh LGTM

2022-11-03 15:16 UTC, e2corporation commented on config-ui/src/components/blueprints/ProviderTransformationSettings.jsx
> +      provider,
Either way is fine, both are correct.

2022-11-03 15:35 UTC, merged