feat(action): add new workflow
apache/incubator-devlake pull request #4436
Opened 2023-02-16 16:04 UTC by warren830

### Summary
First try to automatically upgrade helm

### Does this close any open issues?
Closes xx

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

2023-02-17 05:16 UTC, matrixji requested changes

2023-02-17 05:16 UTC, matrixji commented on .github/workflows/helm-upgrade.yaml
> +          sed -i 's/version:.*/version: ${{ github.ref }}/' charts/devlake/Chart.yaml
Need also to modify `appVersion` in Chart.yaml

2023-02-17 05:16 UTC, matrixji commented on .github/workflows/helm-upgrade.yaml
> +          git push origin version-${{ github.ref }}
Not suggest push commits to master directly, suggest creating PR instead.

2023-02-17 05:16 UTC, matrixji commented on .github/workflows/helm-upgrade.yaml
> +      - name: Commit and Push changes
We could also modify `--version=xxx` in README.md

2023-03-22 01:50 UTC, warren830 commented
fixed by #4607

2023-03-22 01:50 UTC, closed without merging